name: Tests

on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  busted:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        neovim_version: ["stable", "v0.11.0"]

    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Setup neovim
        uses: rhysd/action-setup-vim@v1
        with:
          neovim: true
          version: ${{ matrix.neovim_version }}

      - name: Install Lua
        uses: leafo/gh-actions-lua@v12
        with:
          luaVersion: "5.1"

      - name: Install Luarocks
        uses: leafo/gh-actions-luarocks@v6
        with:
          luarocksVersion: "3.13.0"

      - name: Install dependencies
        run: |
          luarocks install busted
          luarocks install luacov

      - name: Run tests
        run: |
          if [[ "${{ matrix.neovim_version }}" = "stable" ]]; then
            make cov
          else
            make test
          fi
        env:
          LUACOV: ${{ matrix.neovim_version == 'stable' && '1' || '' }}

      - name: Upload coverage to Codecov
        if: matrix.neovim_version == 'stable'
        uses: codecov/codecov-action@v5
        with:
          files: luacov.report.out
          fail_ci_if_error: false
          token: ${{ secrets.CODECOV_TOKEN }}
